### ISSUE TITLE
Container exits straight away

### ISSUE THREAD

**Issue by kilrah** [timothymiller/cloudflare-ddns#103]
Since the last update the container exits straight after launch. The only logged entry is a python error:

`Traceback (most recent call last):
  File "/cloudflare-ddns.py", line 248, in <module>
    print("🕰️ Updating IPv4 (A) records every " + ttl + " seconds")
TypeError: can only concatenate str (not "int") to str`

Looks like the older images got deleted from dockerhub so reverting to a working setup by tagging the previous release is not possible.

**Comment by timothymiller** [comment]
I pushed a fix just now. Can you confirm it fixes the crash issue?

**Comment by kilrah** [comment]
Still crashes with 

`🕰️ Updating IPv4 (A) records every 300 seconds
Traceback (most recent call last):
  File "/cloudflare-ddns.py", line 256, in <module>
    updateIPs(getIPs())
  File "/cloudflare-ddns.py", line 198, in updateIPs
    commitRecord(ip)
  File "/cloudflare-ddns.py", line 109, in commitRecord
    name = subdomain["name"].lower().strip()
TypeError: string indices must be integers`

Note that I do have `""` entries to update the root domain that were referred in #91 if it matters

**Comment by timothymiller** [comment]
I just pushed support for the previous config format. The new format adds a lot more granular control, it might be worth an upgrade.

**Comment by kilrah** [comment]
Updated without changing config, this is what I get:

Traceback (most recent call last):
  File "/cloudflare-ddns.py", line 110, in commitRecord
    name = subdomain["name"].lower().strip()
TypeError: string indices must be integers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cloudflare-ddns.py", line 261, in <module>
    updateIPs(getIPs())
  File "/cloudflare-ddns.py", line 203, in updateIPs
    commitRecord(ip)
  File "/cloudflare-ddns.py", line 114, in commitRecord
    proxied = config["proxied"]
KeyError: 'proxied'
🕰️ Updating IPv4 (A) records every 300 seconds

**Comment by kilrah** [comment]
Looks like old config now works, thanks!
